# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReconOrderUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReconOrderUI(object):
    def setupUi(self, ReconOrderUI):
        ReconOrderUI.setObjectName("ReconOrderUI")
        ReconOrderUI.resize(500, 423)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ReconOrderUI.sizePolicy().hasHeightForWidth())
        ReconOrderUI.setSizePolicy(sizePolicy)
        self.tabWidget = QtWidgets.QTabWidget(ReconOrderUI)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 481, 401))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.main_tab = QtWidgets.QWidget()
        self.main_tab.setObjectName("main_tab")
        self.qbutton_snap_and_correct = QtWidgets.QPushButton(self.main_tab)
        self.qbutton_snap_and_correct.setGeometry(QtCore.QRect(10, 10, 160, 80))
        self.qbutton_snap_and_correct.setAutoDefault(False)
        self.qbutton_snap_and_correct.setObjectName("qbutton_snap_and_correct")
        self.qbutton_collect_background = QtWidgets.QPushButton(self.main_tab)
        self.qbutton_collect_background.setGeometry(QtCore.QRect(300, 10, 160, 80))
        self.qbutton_collect_background.setAutoDefault(False)
        self.qbutton_collect_background.setObjectName("qbutton_collect_background")
        self.qbutton_file_browser = QtWidgets.QPushButton(self.main_tab)
        self.qbutton_file_browser.setGeometry(QtCore.QRect(340, 110, 113, 32))
        self.qbutton_file_browser.setObjectName("qbutton_file_browser")
        self._qlabel_bg_corr_label = QtWidgets.QLabel(self.main_tab)
        self._qlabel_bg_corr_label.setGeometry(QtCore.QRect(10, 120, 171, 16))
        self._qlabel_bg_corr_label.setObjectName("_qlabel_bg_corr_label")
        self.le_bg_corr_path = QtWidgets.QLineEdit(self.main_tab)
        self.le_bg_corr_path.setGeometry(QtCore.QRect(10, 140, 451, 21))
        self.le_bg_corr_path.setObjectName("le_bg_corr_path")
        self.start_monitor = QtWidgets.QPushButton(self.main_tab)
        self.start_monitor.setGeometry(QtCore.QRect(10, 180, 191, 101))
        self.start_monitor.setStyleSheet("background-color: rgb(33, 255, 6);\n"
"color: rgb(0, 0, 0);")
        self.start_monitor.setObjectName("start_monitor")
        self.qbutton_stop_monitor = QtWidgets.QPushButton(self.main_tab)
        self.qbutton_stop_monitor.setGeometry(QtCore.QRect(10, 310, 191, 51))
        self.qbutton_stop_monitor.setStyleSheet("background-color: rgb(252, 1, 7);\n"
"border-color: rgb(252, 1, 7);\n"
"color: rgb(0, 0, 0);")
        self.qbutton_stop_monitor.setAutoDefault(False)
        self.qbutton_stop_monitor.setDefault(False)
        self.qbutton_stop_monitor.setFlat(False)
        self.qbutton_stop_monitor.setObjectName("qbutton_stop_monitor")
        self.label_scale_factor = QtWidgets.QLabel(self.main_tab)
        self.label_scale_factor.setGeometry(QtCore.QRect(240, 180, 91, 16))
        self.label_scale_factor.setFrameShape(QtWidgets.QFrame.Box)
        self.label_scale_factor.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_scale_factor.setLineWidth(1)
        self.label_scale_factor.setObjectName("label_scale_factor")
        self.le_transmission_scale = QtWidgets.QLineEdit(self.main_tab)
        self.le_transmission_scale.setGeometry(QtCore.QRect(340, 210, 113, 21))
        self.le_transmission_scale.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.le_transmission_scale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_transmission_scale.setObjectName("le_transmission_scale")
        self.le_retardance_scale = QtWidgets.QLineEdit(self.main_tab)
        self.le_retardance_scale.setGeometry(QtCore.QRect(340, 240, 113, 21))
        self.le_retardance_scale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_retardance_scale.setObjectName("le_retardance_scale")
        self.le_orientation_scale = QtWidgets.QLineEdit(self.main_tab)
        self.le_orientation_scale.setGeometry(QtCore.QRect(340, 270, 113, 21))
        self.le_orientation_scale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_orientation_scale.setObjectName("le_orientation_scale")
        self.le_polarization_scale = QtWidgets.QLineEdit(self.main_tab)
        self.le_polarization_scale.setGeometry(QtCore.QRect(340, 300, 113, 21))
        self.le_polarization_scale.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_polarization_scale.setObjectName("le_polarization_scale")
        self.label_transmission_scale = QtWidgets.QLabel(self.main_tab)
        self.label_transmission_scale.setGeometry(QtCore.QRect(240, 210, 91, 16))
        self.label_transmission_scale.setObjectName("label_transmission_scale")
        self.label_retardance_scale = QtWidgets.QLabel(self.main_tab)
        self.label_retardance_scale.setGeometry(QtCore.QRect(240, 240, 91, 16))
        self.label_retardance_scale.setObjectName("label_retardance_scale")
        self.label_orientation_scale = QtWidgets.QLabel(self.main_tab)
        self.label_orientation_scale.setGeometry(QtCore.QRect(240, 270, 91, 16))
        self.label_orientation_scale.setObjectName("label_orientation_scale")
        self.label_polarization_scale = QtWidgets.QLabel(self.main_tab)
        self.label_polarization_scale.setGeometry(QtCore.QRect(240, 300, 91, 16))
        self.label_polarization_scale.setObjectName("label_polarization_scale")
        self.tabWidget.addTab(self.main_tab, "")
        self.calibrate_lc_tab = QtWidgets.QWidget()
        self.calibrate_lc_tab.setObjectName("calibrate_lc_tab")
        self.qbutton_calibrate_lc = QtWidgets.QPushButton(self.calibrate_lc_tab)
        self.qbutton_calibrate_lc.setGeometry(QtCore.QRect(160, 10, 160, 80))
        self.qbutton_calibrate_lc.setAutoDefault(False)
        self.qbutton_calibrate_lc.setObjectName("qbutton_calibrate_lc")
        self.le_swing = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_swing.setGeometry(QtCore.QRect(20, 120, 113, 21))
        self.le_swing.setObjectName("le_swing")
        self.le_wavelength = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_wavelength.setGeometry(QtCore.QRect(340, 120, 113, 21))
        self.le_wavelength.setObjectName("le_wavelength")
        self._qlabel_swing = QtWidgets.QLabel(self.calibrate_lc_tab)
        self._qlabel_swing.setGeometry(QtCore.QRect(20, 100, 60, 16))
        self._qlabel_swing.setObjectName("_qlabel_swing")
        self._qlabel_wavelength = QtWidgets.QLabel(self.calibrate_lc_tab)
        self._qlabel_wavelength.setGeometry(QtCore.QRect(340, 100, 81, 16))
        self._qlabel_wavelength.setObjectName("_qlabel_wavelength")
        self.label_state0 = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_state0.setGeometry(QtCore.QRect(20, 190, 60, 16))
        self.label_state0.setObjectName("label_state0")
        self.label_state1 = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_state1.setGeometry(QtCore.QRect(20, 220, 60, 16))
        self.label_state1.setObjectName("label_state1")
        self.label_state2 = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_state2.setGeometry(QtCore.QRect(20, 250, 60, 16))
        self.label_state2.setObjectName("label_state2")
        self.label_state3 = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_state3.setGeometry(QtCore.QRect(20, 280, 60, 16))
        self.label_state3.setObjectName("label_state3")
        self.label_state4 = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_state4.setGeometry(QtCore.QRect(20, 310, 60, 16))
        self.label_state4.setObjectName("label_state4")
        self.le_state0_lca = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state0_lca.setGeometry(QtCore.QRect(80, 190, 61, 21))
        self.le_state0_lca.setReadOnly(True)
        self.le_state0_lca.setObjectName("le_state0_lca")
        self.le_state0_lcb = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state0_lcb.setGeometry(QtCore.QRect(160, 190, 61, 21))
        self.le_state0_lcb.setReadOnly(True)
        self.le_state0_lcb.setObjectName("le_state0_lcb")
        self.le_state1_lca = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state1_lca.setGeometry(QtCore.QRect(80, 220, 61, 21))
        self.le_state1_lca.setReadOnly(True)
        self.le_state1_lca.setObjectName("le_state1_lca")
        self.le_state1_lcb = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state1_lcb.setGeometry(QtCore.QRect(160, 220, 61, 21))
        self.le_state1_lcb.setReadOnly(True)
        self.le_state1_lcb.setObjectName("le_state1_lcb")
        self.le_state2_lca = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state2_lca.setGeometry(QtCore.QRect(80, 250, 61, 21))
        self.le_state2_lca.setReadOnly(True)
        self.le_state2_lca.setObjectName("le_state2_lca")
        self.le_state2_lcb = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state2_lcb.setGeometry(QtCore.QRect(160, 250, 61, 21))
        self.le_state2_lcb.setReadOnly(True)
        self.le_state2_lcb.setObjectName("le_state2_lcb")
        self.le_state3_lca = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state3_lca.setGeometry(QtCore.QRect(80, 280, 61, 21))
        self.le_state3_lca.setReadOnly(True)
        self.le_state3_lca.setObjectName("le_state3_lca")
        self.le_state3_lcb = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state3_lcb.setGeometry(QtCore.QRect(160, 280, 61, 21))
        self.le_state3_lcb.setReadOnly(True)
        self.le_state3_lcb.setObjectName("le_state3_lcb")
        self.le_state4_lca = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state4_lca.setGeometry(QtCore.QRect(80, 310, 61, 21))
        self.le_state4_lca.setReadOnly(True)
        self.le_state4_lca.setObjectName("le_state4_lca")
        self.le_state4_lcb = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state4_lcb.setGeometry(QtCore.QRect(160, 310, 61, 21))
        self.le_state4_lcb.setReadOnly(True)
        self.le_state4_lcb.setObjectName("le_state4_lcb")
        self.label_LCA = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_LCA.setGeometry(QtCore.QRect(80, 170, 60, 16))
        self.label_LCA.setObjectName("label_LCA")
        self.label_LCB = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_LCB.setGeometry(QtCore.QRect(160, 170, 60, 16))
        self.label_LCB.setObjectName("label_LCB")
        self.label_extinction = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_extinction.setGeometry(QtCore.QRect(200, 100, 81, 16))
        self.label_extinction.setObjectName("label_extinction")
        self.le_extinction = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_extinction.setGeometry(QtCore.QRect(180, 120, 113, 21))
        self.le_extinction.setReadOnly(True)
        self.le_extinction.setObjectName("le_extinction")
        self.le_state0_intensity = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state0_intensity.setGeometry(QtCore.QRect(240, 190, 113, 21))
        self.le_state0_intensity.setReadOnly(True)
        self.le_state0_intensity.setObjectName("le_state0_intensity")
        self.le_state1_intensity = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state1_intensity.setGeometry(QtCore.QRect(240, 220, 113, 21))
        self.le_state1_intensity.setReadOnly(True)
        self.le_state1_intensity.setObjectName("le_state1_intensity")
        self.le_state2_intensity = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state2_intensity.setGeometry(QtCore.QRect(240, 250, 113, 21))
        self.le_state2_intensity.setReadOnly(True)
        self.le_state2_intensity.setObjectName("le_state2_intensity")
        self.le_state3_intensity = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state3_intensity.setGeometry(QtCore.QRect(240, 280, 113, 21))
        self.le_state3_intensity.setReadOnly(True)
        self.le_state3_intensity.setObjectName("le_state3_intensity")
        self.le_state4_intensity = QtWidgets.QLineEdit(self.calibrate_lc_tab)
        self.le_state4_intensity.setGeometry(QtCore.QRect(240, 310, 113, 21))
        self.le_state4_intensity.setReadOnly(True)
        self.le_state4_intensity.setObjectName("le_state4_intensity")
        self.label_intensity = QtWidgets.QLabel(self.calibrate_lc_tab)
        self.label_intensity.setGeometry(QtCore.QRect(240, 170, 60, 16))
        self.label_intensity.setObjectName("label_intensity")
        self.tabWidget.addTab(self.calibrate_lc_tab, "")
        self.logs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logs.sizePolicy().hasHeightForWidth())
        self.logs.setSizePolicy(sizePolicy)
        self.logs.setObjectName("logs")
        self.scrollArea = QtWidgets.QScrollArea(self.logs)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 481, 371))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 369))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.log_area = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.log_area.setGeometry(QtCore.QRect(0, 0, 481, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.log_area.setFont(font)
        self.log_area.setAcceptDrops(False)
        self.log_area.setObjectName("log_area")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.logs, "")

        self.retranslateUi(ReconOrderUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ReconOrderUI)

    def retranslateUi(self, ReconOrderUI):
        _translate = QtCore.QCoreApplication.translate
        ReconOrderUI.setWindowTitle(_translate("ReconOrderUI", "ReconOrder"))
        self.qbutton_snap_and_correct.setText(_translate("ReconOrderUI", "Snap and BG Correct"))
        self.qbutton_collect_background.setText(_translate("ReconOrderUI", "Collect Background"))
        self.qbutton_file_browser.setText(_translate("ReconOrderUI", "Browse"))
        self._qlabel_bg_corr_label.setText(_translate("ReconOrderUI", "Background correction file"))
        self.start_monitor.setText(_translate("ReconOrderUI", "Monitor and reconstruct"))
        self.qbutton_stop_monitor.setText(_translate("ReconOrderUI", "Stop Monitor"))
        self.label_scale_factor.setText(_translate("ReconOrderUI", "Scale factor"))
        self.le_transmission_scale.setText(_translate("ReconOrderUI", "100000"))
        self.le_retardance_scale.setText(_translate("ReconOrderUI", "100000"))
        self.le_orientation_scale.setText(_translate("ReconOrderUI", "1000000"))
        self.le_polarization_scale.setText(_translate("ReconOrderUI", "100"))
        self.label_transmission_scale.setText(_translate("ReconOrderUI", "transmission"))
        self.label_retardance_scale.setText(_translate("ReconOrderUI", "retardance"))
        self.label_orientation_scale.setText(_translate("ReconOrderUI", "orientation"))
        self.label_polarization_scale.setText(_translate("ReconOrderUI", "polarization"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), _translate("ReconOrderUI", "Snap and BG"))
        self.qbutton_calibrate_lc.setText(_translate("ReconOrderUI", "Calibrate LC"))
        self.le_swing.setText(_translate("ReconOrderUI", "0.03"))
        self.le_wavelength.setText(_translate("ReconOrderUI", "532"))
        self._qlabel_swing.setText(_translate("ReconOrderUI", "Swing"))
        self._qlabel_wavelength.setText(_translate("ReconOrderUI", "Wavelength"))
        self.label_state0.setText(_translate("ReconOrderUI", "State 0"))
        self.label_state1.setText(_translate("ReconOrderUI", "State 1"))
        self.label_state2.setText(_translate("ReconOrderUI", "State 2"))
        self.label_state3.setText(_translate("ReconOrderUI", "State 3"))
        self.label_state4.setText(_translate("ReconOrderUI", "State 4"))
        self.label_LCA.setText(_translate("ReconOrderUI", "LCA"))
        self.label_LCB.setText(_translate("ReconOrderUI", "LCB"))
        self.label_extinction.setText(_translate("ReconOrderUI", "Extinction"))
        self.label_intensity.setText(_translate("ReconOrderUI", "Intensity"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibrate_lc_tab), _translate("ReconOrderUI", "Calibrate LC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.logs), _translate("ReconOrderUI", "logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReconOrderUI = QtWidgets.QDialog()
    ui = Ui_ReconOrderUI()
    ui.setupUi(ReconOrderUI)
    ReconOrderUI.show()
    sys.exit(app.exec_())

